### ISSUE TITLE
the difference between nnet and nkn-sdk-go

### ISSUE THREAD

**Issue by Nyx2022** [nknorg/nnet#39]
i wanna know the difference between nnet and nkn-sdk-go,can you tell me in chinese?

**Comment by yilunzhang** [comment]
`nnet` is the p2p network layer that lets you build your own p2p network, like `libp2p`. It's typically NOT used on client side (e.g. mobile app, web app, etc) because:
1. it requires all or most peers to be able to receive incoming connections, which are not feasible for most clients. 
2. each node needs to maintain (relatively) a large amount of peer connections, and the resource consumption will be proportional to the number of connections

NKN SDK (go, js, or any other version), on the other hand, is meant to be used on client side. It doesn't require clients to receive any incoming connections, and each client/multiclient only maintain 1/4 connections.

Under the hood, NKN SDK creates NKN clients, which connect to NKN nodes and use them to send/receive data. NKN nodes uses `nnet` to form a p2p network and relay data.
