### ISSUE TITLE
Need provide more specific description about message send apis

### ISSUE THREAD

**Issue by Cishanduwang** [nknorg/nnet#47]
For example SendBytesDirectSync . I want to use this function to send message from A to B, but this function need a type *node.RemoteNode as parameter. So i need to create a  node.RemoteNode struct for B? I don't know how to create it.

Middleware callback function will provide *node.RemoteNode , so does this mean this function only can be used in middleware callback function?

Thank you.

**Comment by yilunzhang** [comment]
SendBytesDirectSync is used to send message to your direct neighbor. Generally in any DHT you don't directly control who are your direct neighbors, each DHT has its own protocol to dynamically update neighbors for each node as nodes join or leave the network. Specifically in Chord DHT, each node's neighbors include successors, predecessors, finger tables, you can get those neighbors using methods such as [Successors()](https://github.com/nknorg/nnet/blob/master/overlay/chord/chord.go#L657C17-L657C27).

But since you are using DHT, chances are that you don't want to send messages to your direct neighbors. Most of the times you will want to send message to a node by its ID, regardless of whether it's your direct neighbor or not. After all, that's one of the main reasons to use DHT: don't worry about topology. If that's your case, you might want to use methods such as `SendBytesRelaySync`, like in [this example](https://github.com/nknorg/nnet/blob/master/examples/message/main.go#L128C35-L128C53). You just need the ID of the node.

**Comment by Cishanduwang** [comment]
Hi, Thank you for your replay. But i have a few more question about message apis.
I have try these functions SendBytesDirectReply,SendBytesRelayReply and SendBytesBroadcastReply . Does these functions only used in middleware to replay messages? 
As for SendBytesBroadcastSync , this function will broadcast message to every node and wait for replay . but it seems it can only receive one reply ，other reply will be drop because the channel is full. so this makes me feel weird. Am I using it correctly?

**Comment by yilunzhang** [comment]
> I have try these functions SendBytesDirectReply,SendBytesRelayReply and SendBytesBroadcastReply . Does these functions only used in middleware to replay messages?

You don't have to use them in middleware, you can call them in anywhere as long as you have information like msg ID, src ID, etc. But it's most convenient to use them in middleware because the middleware callback parameters have those information ready.

> As for SendBytesBroadcastSync , this function will broadcast message to every node and wait for replay . but it seems it can only receive one reply ，other reply will be drop because the channel is full. so this makes me feel weird. Am I using it correctly?

We do this on purpose because nnet is designed to use in large distributed systems (e.g. we have 100k+ nodes), in which case it's not practical to wait for reply from every node, and it's essentially DDoS the sender node. Broadcast message don't typically have any "reply" logic because of this reason. If you need information back from multiple nodes who receive your broadcast message, I would recommend using `SendBytesBroadcastAsync` to send broadcast message, and let those nodes send back reply using `SendBytesRelayAsync`.

**Comment by Cishanduwang** [comment]
Thank you for your patient reply.
